[package]
name = "casey"
version = "0.1.1"
authors = ["holygits <beauchjord@gmail.com>"]
edition = "2018"
description = "Case transforming macros for ident tokens"
license = "MIT"
readme = "README.md"
repository = "https://github.com/holygits/casey"

[lib]
proc-macro = true

[dependencies]
heck = "0.3.1"
